# NumPy

- Short form of Numerical Python.
- Similar to python list.
- Dynamic typecasting in Python adds overhead. 
- Much more efficent for storage and operation. Especially as data size grows.

For future http://www.numpy.org/ and https://jakevdp.github.io/PythonDataScienceHandbook/index.htmlis your best friend.

In [9]:
import numpy as np

## Python list to array

In [10]:
[1,2,3,4]

[1, 2, 3, 4]

In [15]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [17]:
type(a[0])

numpy.int64

In [5]:
[3.14,4,2,3], np.array([3.14,4,2,3])

([3.14, 4, 2, 3], array([3.14, 4.  , 2.  , 3.  ]))

In [19]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [28]:
a = np.array([range(i,i+3) for i in [2,4,6]])

In [33]:
a = np.array([3.14,4,2,3])
a.dtype

dtype('float64')

## Creating array from scratch 

In [35]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full((9, 9), 1001)

array([[1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001]])

In [46]:
[i for i in range(1,10,2)]

[1, 3, 5, 7, 9]

In [69]:
np.arange(0, 20,5)

array([ 0,  5, 10, 15])

In [53]:
np.linspace(0, 150,20)

array([  0.        ,   7.89473684,  15.78947368,  23.68421053,
        31.57894737,  39.47368421,  47.36842105,  55.26315789,
        63.15789474,  71.05263158,  78.94736842,  86.84210526,
        94.73684211, 102.63157895, 110.52631579, 118.42105263,
       126.31578947, 134.21052632, 142.10526316, 150.        ])

In [86]:
a = np.random.random((3, 3))
a

array([[0.75243255, 0.01811254, 0.50042907],
       [0.86042296, 0.44711593, 0.35021951],
       [0.70458076, 0.84484432, 0.58533328]])

In [90]:
a.astype("int16")


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [74]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
a = np.array([np.random.randint(1,150) for i in range(20)])

In [85]:
a.astype('float32')

array([134., 144.,  93., 129.,  40.,  61.,  82., 142., 149., 143.,  94.,
        97.,   7., 123., 137., 102.,  57., 107., 113.,  23.],
      dtype=float32)

## Array attributes

In [110]:
x = np.random.random((3, 6,4))
# x = np.arange(0,10)

In [111]:
x

array([[[0.96304363, 0.0779551 , 0.08185466, 0.80984579],
        [0.42715647, 0.24178978, 0.01839234, 0.95687154],
        [0.97271844, 0.63080723, 0.03387113, 0.94223846],
        [0.66785061, 0.18073806, 0.89417449, 0.80740679],
        [0.33057262, 0.59897191, 0.90760199, 0.43440818],
        [0.10800215, 0.79349507, 0.11537502, 0.33419081]],

       [[0.50301139, 0.46983944, 0.38772196, 0.36220838],
        [0.94562224, 0.27616703, 0.6552869 , 0.8417461 ],
        [0.76575947, 0.94225758, 0.67718323, 0.36149663],
        [0.11553421, 0.94483155, 0.41335477, 0.22215276],
        [0.72289311, 0.83565705, 0.42340274, 0.52202127],
        [0.61410011, 0.45154823, 0.34443654, 0.0443107 ]],

       [[0.47000534, 0.45545957, 0.29189811, 0.7389282 ],
        [0.81440179, 0.09219675, 0.34225617, 0.98318791],
        [0.74561996, 0.19730255, 0.75749063, 0.27250049],
        [0.21873331, 0.56886247, 0.17918998, 0.30839681],
        [0.11550064, 0.50290415, 0.2573927 , 0.8290003 ],
        [0

In [112]:
x.shape

(3, 6, 4)

In [113]:
x.ndim

3

In [104]:
x.size

10

In [105]:
x.dtype

dtype('int64')

## Array Indexing 

In [115]:
x = np.linspace(0, 1, 5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [116]:
x[0]

0.0

In [117]:
x[3]

0.75

In [118]:
x[7]

IndexError: index 7 is out of bounds for axis 0 with size 5

In [119]:
x[-2]

0.75

In [126]:
x = np.random.random((3, 3))
x

array([[0.77027457, 0.93372939, 0.80381727],
       [0.96839644, 0.48102598, 0.28558451],
       [0.77035967, 0.0046356 , 0.44322743]])

In [127]:
x[0]

array([0.77027457, 0.93372939, 0.80381727])

In [129]:
x[0,2]

0.8038172669791348

In [130]:
x[0][2]

0.8038172669791348

In [132]:
x

array([[0.77027457, 0.93372939, 0.80381727],
       [0.96839644, 0.48102598, 0.28558451],
       [0.77035967, 0.0046356 , 0.44322743]])

In [137]:
x[1,2] = 0.99999

In [139]:
x

array([[0.77027457, 0.93372939, 0.80381727],
       [0.96839644, 0.48102598, 0.99999   ],
       [0.77035967, 0.0046356 , 0.44322743]])

In [147]:
x = np.linspace(0, 1, 10)
x

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [150]:
x = np.random.random((3, 3))
x

array([[0.01753415, 0.50433614, 0.55817829],
       [0.12561661, 0.45617191, 0.46764014],
       [0.65436839, 0.44418334, 0.25892737]])

## Array Slicing 

In [156]:
a = list(range(0,50))

In [163]:
a[::2]

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [209]:
x = np.random.random(10)
x

array([0.48232828, 0.53205005, 0.45525377, 0.78350094, 0.49245826,
       0.90555571, 0.10639442, 0.30503412, 0.57352762, 0.77733104])

In [210]:
x[:5]

array([0.48232828, 0.53205005, 0.45525377, 0.78350094, 0.49245826])

In [211]:
x[5:]

array([0.90555571, 0.10639442, 0.30503412, 0.57352762, 0.77733104])

In [212]:
x[4:7]

array([0.49245826, 0.90555571, 0.10639442])

In [213]:
x[::2]

array([0.48232828, 0.45525377, 0.49245826, 0.10639442, 0.57352762])

In [219]:
x[3:8:2]

array([0.78350094, 0.90555571, 0.30503412])

In [220]:
x[8:3:-2]

array([0.57352762, 0.10639442, 0.49245826])

In [222]:
x = np.array([range(i,i+5) for i in [2,4,6,9]])

In [223]:
x

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10],
       [ 9, 10, 11, 12, 13]])

In [228]:
x[1:3, 1:4]

array([[5, 6, 7],
       [7, 8, 9]])

In [202]:
x[:, ::2]  # all rows, every other column

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [227]:
x[::-1,:]

array([[ 9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6]])

In [241]:
np.array([[[[k for k in range(3)] for j in range(4)] for i in range(5)] for a in range(10)])

array([[[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0,

## Concatenation of arrays

In [242]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [65]:
x,y

(array([1, 2, 3]), array([3, 2, 1]))

In [243]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [244]:
x = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [245]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [247]:
np.concatenate([x,x], axis=0) # concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [248]:
np.concatenate([x, x], axis=1) # concatenate along the second axis (zero-indexed)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [249]:
x = np.array([1, 2, 3])
y = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [250]:
x

array([1, 2, 3])

In [251]:
y

array([[9, 8, 7],
       [6, 5, 4]])

In [252]:
np.vstack([x, y])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [253]:
z = np.array([[99],
              [99]])

In [254]:
np.hstack([y, z])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Array split

In [256]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [258]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [84]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Numpy Universal Function

These are the standard method to operate on numpy arrays and core of why it is do fast 

In [260]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [262]:
x = np.random.randint(1, 10, size=5)
x

array([6, 4, 3, 4, 7])

In [88]:
%timeit compute_reciprocals(x)

20.2 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [89]:
%timeit 1.0/x

1.74 µs ± 73.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [90]:
big_array = np.random.randint(1, 100, size=1000000)

In [92]:
%timeit compute_reciprocals(big_array)
%timeit 1.0/big_array

3.41 s ± 111 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.76 ms ± 55.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


The speed is mostly achived due to reduction in type casting/checking overhead and Vectorized operations

In [94]:
np.arange(5) / 2.0 # works on scaler and array

array([0. , 0.5, 1. , 1.5, 2. ])

In [95]:
np.arange(5) / np.arange(1, 6) # works with two arrays

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [97]:
# multidimensional arrays too
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Arithmetic Operations 

In [285]:
x = np.arange(9).reshape((3, 3))
y = np.arange(10,19).reshape((3, 3))

In [286]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [287]:
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [288]:
x+y

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [289]:
x-y

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [290]:
x*y

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [291]:
x**y

array([[                0,                 1,              4096],
       [          1594323,         268435456,       30517578125],
       [    2821109907456,   232630513987207, 18014398509481984]])

All above operations also works with scalar values

In [292]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [294]:
x/y/5

array([[0.        , 0.01818182, 0.03333333],
       [0.04615385, 0.05714286, 0.06666667],
       [0.075     , 0.08235294, 0.08888889]])

### Other math opearations

In [282]:
x = np.linspace(0, np.pi, 3)

In [283]:
x

array([0.        , 1.57079633, 3.14159265])

In [120]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.exp(x))
print(np.log(x))
print(np.log10(x))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[ 1.          4.81047738 23.14069263]
[      -inf 0.45158271 1.14472989]
[      -inf 0.19611988 0.49714987]


<ipython-input-120-cf2060ae3e6d>:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(x))
<ipython-input-120-cf2060ae3e6d>:6: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(x))


In [123]:
x = np.arange(9).reshape((3, 3))
y = np.arange(10,19).reshape((3, 3))

In [124]:
np.matmul(x,y)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

### Statistical operations

In [127]:
L = np.random.random(10000000)

In [128]:
%timeit sum(L)
%timeit np.sum(L)

2.66 s ± 71.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.13 ms ± 182 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [129]:
sum(L), np.sum(L)

(5002417.5887549985, 5002417.588754766)

In [130]:
min(L), max(L)

(3.3613458449988087e-07, 0.999999940358766)

In [131]:
np.min(L), np.max(L)

(3.3613458449988087e-07, 0.999999940358766)

In [132]:
%timeit min(L)
%timeit np.min(L)

1.65 s ± 28.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.92 ms ± 139 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Works on Multiple dimension arrays too

In [133]:
M = np.random.random((3, 4))
M

array([[0.05823697, 0.42838908, 0.96296755, 0.91907014],
       [0.54157888, 0.46248073, 0.03324701, 0.23858661],
       [0.21765615, 0.99854484, 0.81641322, 0.31391802]])

In [134]:
M.sum()

5.991089177295053

In [135]:
M.sum(axis=0)

array([0.81747199, 1.88941464, 1.81262778, 1.47157477])

In [136]:
M.sum(axis=1)

array([2.36866373, 1.27589322, 2.34653223])

Few other widely used functions are

In [137]:
np.mean(M)

0.4992574314412544

In [138]:
np.std(M)

0.33448660480691517

In [140]:
np.argmin(M),np.argmax(M)

(6, 9)